name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin

      - name: Build Docker Compose services
        run: docker compose -f docker-compose.yml build

      - name: Start Docker Compose services
        run: docker compose -f docker-compose.yml up -d

      - name: Wait for services to become healthy
        run: docker compose -f docker-compose.yml ps

      - name: Run Cypress tests
        run: docker compose -f docker-compose.yml run cypress

      - name: Shutdown Docker Compose
        run: docker compose -f docker-compose.yml down --volumes
